# Generated by Django 4.2.6 on 2024-03-11 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiHitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('time_refreshed', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_hits', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.team')),
            ],
        ),
    ]
